name: Run Strava / Coros Data Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
      - ok
      - workouts
    paths:
      - run_page/nike_sync.py
      - run_page/strava_sync.py
      - run_page/gen_svg.py
      - run_page/garmin_sync.py
      - run_page/coros_sync.py
      - run_page/keep_sync.py
      - run_page/gpx_sync.py
      - run_page/tcx_sync.py
      - run_page/fit_sync.py
      - requirements.txt

env:
  RUN_TYPE: coros
  ATHLETE: 蓝皮书
  TITLE: Workouts
  MIN_GRID_DISTANCE: 10
  TITLE_GRID: Over 10km Workouts

  IGNORE_START_END_RANGE: 0
  IGNORE_POLYLINE: ""
  IGNORE_RANGE: 0
  SAVE_DATA_IN_GITHUB_CACHE: false
  DATA_CACHE_PREFIX: 'track_data'
  BUILD_GH_PAGES: false
  SAVE_TO_PARQENT: false
  GENERATE_MONTH_OF_LIFE: false
  BIRTHDAY_MONTH: 1994-12
  VITE_LAT_OFFSET: ${{ secrets.VITE_LAT_OFFSET }}
  VITE_LNG_OFFSET: ${{ secrets.VITE_LNG_OFFSET }}

jobs:
  sync:
    name: Sync Workout Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run sync Coros script (高驰)
        if: env.RUN_TYPE == 'coros'
        run: |
          python run_page/coros_sync.py ${{ secrets.COROS_ACCOUNT }} ${{ secrets.COROS_PASSWORD }}

      - name: Run sync Strava script
        if: env.RUN_TYPE == 'strava'
        run: |
          python run_page/strava_sync.py ${{ secrets.STRAVA_CLIENT_ID }} ${{ secrets.STRAVA_CLIENT_SECRET }} ${{ secrets.STRAVA_CLIENT_REFRESH_TOKEN }}

      - name: Run sync Garmin script
        if: env.RUN_TYPE == 'garmin'
        run: |
          python run_page/garmin_sync.py ${{ secrets.GARMIN_SECRET_STRING }}

      - name: Run sync Keep script
        if: env.RUN_TYPE == 'keep'
        run: |
          python run_page/keep_sync.py ${{ secrets.KEEP_MOBILE }} ${{ secrets.KEEP_PASSWORD }} --with-gpx

      - name: Update activities data (Privacy)
        if: env.RUN_TYPE != 'pass'
        env:
          VITE_LAT_OFFSET: ${{ secrets.VITE_LAT_OFFSET }}
          VITE_LNG_OFFSET: ${{ secrets.VITE_LNG_OFFSET }}
        run: |
          python3 run_page/update_activities_file.py

      - name: Make svg GitHub profile
        if: env.RUN_TYPE != 'pass'
        env:
          TITLE: ${{ env.TITLE }}
          TITLE_GRID: ${{ env.TITLE_GRID }}
          ATHLETE: ${{ env.ATHLETE }}
          MIN_GRID_DISTANCE: ${{ env.MIN_GRID_DISTANCE }}
        run: |
          python run_page/gen_svg.py --from-db --title "$TITLE" --type github --github-style "align-firstday" --athlete "$ATHLETE" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5
          python run_page/gen_svg.py --from-db --title "$TITLE_GRID" --type grid --athlete "$ATHLETE" --output assets/grid.svg --special-color yellow --special-color2 red --special-distance 20 --special-color2 red --use-localtime --min-distance "$MIN_GRID_DISTANCE"
          python run_page/gen_svg.py --from-db --type circular --use-localtime
          python run_page/gen_svg.py --from-db --year $(date +"%Y")  --language zh_CN --title "$(date +"%Y") Workouts" --type github --github-style "align-firstday" --athlete "$ATHLETE" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github_$(date +"%Y").svg --use-localtime --min-distance 0.5

      - name: Push new runs
        if: env.SAVE_DATA_IN_GITHUB_CACHE != 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "sync: update workouts data [$(date +'%Y-%m-%d %H:%M:%S')]" || echo "nothing to commit"
          git push origin ${GITHUB_REF#refs/heads/} || echo "nothing to push"
